name: norminette
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  norminette:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install norminette
    - name: Lint with norminette
      run: |
        echo "Running norminette..."
        
        # Run norminette and save output to file
        norminette . > norminette_results.txt 2>&1
        cat norminette_results.txt
        
        # Count errors and warnings
        error_count=$(grep -c "Error:" norminette_results.txt || echo "0")
        warning_count=$(grep -c "Warning:" norminette_results.txt || echo "0")

        # Fail if any errors or warnings found
        if [ "$error_count" -gt 0 ] || [ "$warning_count" -gt 0 ]; then
          echo "❌ Norminette found $error_count errors and $warning_count warnings!"
          exit 1
        fi
        
        echo "✅ Norminette check passed!"
